### ISSUE TITLE
Moneta benchmark totally opposite from these

### ISSUE THREAD

**Issue by dare05** [minad/moneta#113]
I'm comparing Moneta benchmarks to https://gist.github.com/stephan-nordnes-eriksen/6c9c56f63f36d5d100b2 and they're totally opposite. In this Benchmark, daybreak is ultimately the slowest implementation, while GDBM/DBM/PStore are fairly fast. Why such a big difference?

**Comment by asppsa** [comment]
Hi there,

I'm not sure, but the author's suggestion that the difference is due to the number of keys being used in the benchmarks is plausible.  Perhaps Daybreak only outperforms for fewer keys.  It could also be something to do with the environments that the benchmarks are being run in (i.e. the author's own machine vs. Travis CI; different Ruby versions, etc.).

You could perhaps test these theories for us by running both the test script given at that gist and our own `script/benchmarks` with similar numbers of keys on the same machine.  For the latter, you can edit the `CONFIGS` list in `script/benchmarks` to add a benchmark profile with a comparable number of keys.   If you do this, please let us know how you go!

**Comment by wjordan** [comment]
The difference doesn't have to do with the number of keys, but rather with what exactly is being benchmarked.

In the gist, all of the benchmarks contain `db.stop`, which for `daybreak` (`Daybreak::DB#close`) synchronously flushes all data to disk and closes the database file, which is a slow operation that skews all results (especially the non-insert benchmarks).

If you move `db.stop` outside of the benchmark block, `daybreak` is much faster, however the asynchronous insert operations will make the final database-close operation take a while (the inserts are not actually persisted to disk until the flush operation occurs). If you include a synchronous `db.flush` within each benchmark iteration, `daybreak` is still the slowest for insert operations.

For all non-insert operations, `daybreak` is always just as fast as `hash` (since it uses a memory hash of the database contents for these operations).

See an [updated gist](https://gist.github.com/wjordan/e1e0d735be576e8fcc3385886ff0e32d) for updated benchmark code and results.

**Comment by dare05** [comment]
@wjordan a bit late here.

I've noticed that PStore performance degrades significantly the bigger the database is. Especially if you  do reads inside a single transaction vs DayBreak, try this with a db of a million records and DayBreak completes almost 30x as fast as PStore.
