### ISSUE TITLE
[Feature Request] implement read_multi and fetch_multi using mget and mset

### ISSUE THREAD

**Issue by tony612** [minad/moneta#116]
The original implementation is inefficient https://github.com/rails/rails/blob/8fa5840f344ce10d776bde82fb49309c7b751bc0/activesupport/lib/active_support/cache.rb#L338

**Comment by asppsa** [comment]
Hi there,

`mget` and `mset` aren't part of the [Moneta API](https://github.com/minad/moneta#moneta-api). I guess you are talking about the Redis backend?

In order for our ActiveSupport cache implementation to support `read_multi` and friends, I believe the process would need to be:

1. add a new [feature](https://github.com/minad/moneta#backend-feature-matrix) to the Moneta API (e.g. "multi"), with methods like `fetch_multi`, etc; 
2. adapters (e.g. redis) would need to be extended to implement this feature, where possible.

This is doable in theory!

**Comment by tony612** [comment]
@asppsa Yes, I mean the Redis backend.

**Comment by asppsa** [comment]
I think some kind of batching support would definitely be valuable.  Because moneta has so many backends, some thought needs to be given to what kind of API can be implemented in the most backends.

In the meantime though, if speed is your concern, have you considered using an activesupport cache implementation that is specifically optimised for Redis?  I am not an expert on this, but I a quick look around turned up [readthis](https://github.com/sorentwo/readthis/blob/master/PERFORMANCE.md).
