### ISSUE TITLE
Support for pair enumeration

### ISSUE THREAD

**Issue by asppsa** [minad/moneta#151]
@brutuscat, I'm keen to hear your views on the following issue. Sorry this is a bit long!

I've been thinking about what needs to happen in order to be able to reliably enumerate all the pairs in a store.  The problem I've noticed with what we have presently is that a naive implementation of `each_pair` like the following is not going to be safe in a multithread or multiprocess environment:

~~~ ruby
def each_pair
  return enum_for(:each_pair) unless block_given?
  each_key do |key|
    yield [key, load(key)]
  end
end
~~~

In the above implementation, if there are two processes accessing a store at once, and the first process calls `each_pair`, and the second process does a `delete('somekey')`, we have a race condition and the first process *might* (e.g. if the backend returns all keys immediately as an array) `yield ['somekey', nil]`.  The code wouldn't then be able to tell if the key had been deleted or if the value associated with 'somekey' was actually nil in the store.  The way to resolve this would be to check via a call to `key?`, but then there would need to be some locking or something in between the `key?` call and the `load` call (in case the value was deleted in between), which doesn't seem good.  

This seems to point to the need for a separate feature that stores can advertise to indicate they can do pair enumeration without races. Conversely though, implementing `each_key` based on `each_pair` is safe in the sense outlined above.  Given this, I am wondering if we should maybe rethink the `each_key` feature, and maybe rename it to `each_pair` (or maybe just call it `each`).  In other words, the fundamental thing that we need stores to support in order to do enumeration is `each_pair`. We would still keep the `each_key` method in the spec as part of the `each_pair` feature -- we would require both methods to be provided by all adapters with the feature. For backends where `each_key` is implemented on `each` anyway, we could have a default version of `each_key` based on `each_pair`.

I know you've spent a lot of time on this already and I wouldn't want to undo all of that work. I think though that this change could be done without affecting your work too much in the following way:

1. keep all of your `each_key` implementations on the various adapters, but supplement them with `each_pair` implementations also.
2. replace all of the `supports :each_key` lines with `supports :each_pair` (simple find-replace)
3. replace the `each_key` implementation in `Moneta::Defaults` (currently just raises an error) with one that calls `each_pair` if the store `supports :each_pair` & raises like it currently does otherwise.
4. update the specs and docs

We could also make something like `EachPairFromEachKeySupport` (similar to existing `IncrementSupport`) for stores where it's only possible to implement `each_key`. This would provide a naive `each_pair` implementation like the one I gave above.

Alternatively, we could keep the `each_key` feature and add an `each_pair` feature as well, but then to me this seems like overkill, given that it should always be possible to support `each_key` whenever `each_pair` is supported.

**Comment by brutuscat** [comment]
@asppsa I will read this more in detail and try to get you a better answer, but after scanning this (just for a quick "lets discuss" feedback) my guy feeling is that we should not try to solve the backends lack of ACID properties... Anything on those lines to me is, honestly, a leak of the abstraction.

If the backend does not give us a way to control the serializability properties of each operation then well it shoudl not be used concurrently as you are intending... Since it was never meant to be!

I think I answer to you something on these lines before https://github.com/minad/moneta/pull/134#issuecomment-373966805

**Comment by brutuscat** [comment]
As a example (I still have to consider what you suggested) and following the line of thought from the other comment, MySQL and other databases allows you to control this on each transaction ([transaction isolation levels](https://dev.mysql.com/doc/refman/8.0/en/innodb-transaction-isolation-levels.html)). As a user of the db you know what to expect when using each key and each value on different threads

**Comment by brutuscat** [comment]
This is a good article about the usual cases that one has to deal with https://begriffs.com/posts/2017-08-01-practical-guide-sql-isolation.html

**Comment by brutuscat** [comment]
BTW I am reading things like this to understand how other bigger projects are dealing with this problem https://apacheignite.readme.io/docs/transactions scroll down and you will see a bunch of links about different consensus protocols that I think is useful to understand better the depth of the problem you are trying to solve here.

**Comment by asppsa** [comment]
I agree that it would be silly/impossible to try to guarantee isolation such that the store doesn't change during a block call from `each_key` or whatever. What I was trying (badly) to get at is that precisely because we can't have this kind of isolation, I think that the only "reliable" way to do an `each_pair` method in Moneta is going to be via the native methods offered by the backends (e.g. the `each` methods of Hash and friends, and whatever makes sense on SQL backends, etc.), and not via some wrapper over `each_key`.  Using the backend methods should at least guarantee that whenever a key-value pair is yielded by the enumerator, that key and value were together in the store at some stage, which is what I mean by "reliable" (unlike the `['somekey', nil]` example I gave in the last post).

This in turn suggests that rather than requiring adapters to implement `each_key` as the most basic method for enumeration, we should be requiring that they implement `each_pair` (AKA `each`) as well (with a default `each_key`implementation based on `each_pair` as fall-back).  What do you reckon?

**Comment by brutuscat** [comment]
@asppsa TBH it is really about what one would expect (or not) from the desired consistency model (e.g. SQL databases give you like 4 or more consistency models and all are tied to a transaction).

I don't agree on some of your points. For example, in a DB like MySQL if you read the whole table (or if we would optimise this and make it a batch read), by default (REPEATABLE READ) it will take a "snapshot" and all the reads on that transaction will not seem affected by any delete or update on the database, so there is not "race" here.  Now on different isolation levels, different locks are taken based on what level of consistency you feel confortable with. 

Now for something like Redis, since we use SCAN for listing the keys, there are [other set of guarantees](https://redis.io/commands/scan#scan-guarantees). This almost certainly won't match any of the guarantees of other backends. For example it says:
> A given element may be returned multiple times. It is up to the application to handle the case of duplicated elements, for example only using the returned elements in order to perform operations that are safe when re-applied multiple times.

As you can see this is very incompatible with other backends too... So deciding the consistency model by the user of the gem will not end well, neither trying (naively) to "fix" the race condition or normalise the iteration behaviour across competing operations.

I could do the changes as you said, where it makes sense, and we could later on discuss how to add some locking mechanism via some mixin, so to allow the user to "block" other operations from "changing" the each key/value collection while the are reading from it. We could even also explore how to, with backends that support it, send options to control consistency models instead of using locking at our end.

**Comment by asppsa** [comment]
@brutuscat, I definitely do not want to have to introduce some kind of locking mechanism when enumerating pairs. I think the best approach for now is just to try to get `each_key` implemented on as many adapters as possible.  Given that, I'll close this for the time being.
